import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../app/navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Techcrucks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>

) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full p-[20px]">
          <div className="bg-[#f5f5f5]">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
